/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) throws Exception {
        String url = "http://127.0.0.1:7000";
        MyConnectionHandler handler = new MyConnectionHandler();
        handler.createConnection(url);
        handler.createConnection(url);

        String echo = handler.sendResponse(0, "get");
        System.out.println(echo);

        echo = handler.sendResponse(1, "get");
        System.out.println(echo);

        echo = handler.sendResponse(0, "set 20");
        System.out.println(echo);

        echo = handler.sendResponse(0, "get");
        System.out.println(echo);

        echo = handler.sendResponse(1, "get");
        System.out.println(echo);

        Thread.sleep(2000);
        handler.closeAll();
        // MyQuicClient client = new MyQuicClient(url);
        //
        // client.connect();
        // client.sendUnidirectional("idk ich send einfach");
        // String echo = client.sendResponse("echo pls");
        // System.out.println(echo);
        //
        // int stream_id = client.open_stream();
        // client.send_msg_over(stream_id, "send over 1");
        //
        // Thread.sleep(2000);
        //
        // int stream_id2 = client.open_stream();
        // client.send_msg_over(stream_id2, "send over 2");
        //
        // Thread.sleep(2000);
        //
        // client.send_msg_over(stream_id, "send over 1, 2");
        //
        // client.close();
    }
}
