/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.OutputStream;
import java.net.URI;

import tech.kwik.core.QuicClientConnection;
import tech.kwik.core.QuicStream;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("hi from client");
        QuicClientConnection connection = QuicClientConnection.newBuilder()
                .noServerCertificateCheck()
                .uri(URI.create("http://127.0.0.1:7000"))
                .applicationProtocol("quic")
                .build();

        connection.connect();

        QuicStream quicStream = connection.createStream(true);
        OutputStream output = quicStream.getOutputStream();
        output.write(10);
        output.close();
    }
}
