/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) throws Exception {
        String url = "http://127.0.0.1:7000";
        MyQuicClient client = new MyQuicClient(url);

        client.connect();
        client.send("idk ich send einfach");
        try {
            Thread.sleep(7000);
        } catch (InterruptedException e) {
            // do nothing
        }
        client.close();
    }
}
