/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.FileInputStream;
import java.security.KeyStore;
import java.util.ArrayList;
import java.util.List;

import tech.kwik.core.QuicConnection;
import tech.kwik.core.log.Logger;
import tech.kwik.core.log.SysOutLogger;
import tech.kwik.core.server.ServerConnectionConfig;
import tech.kwik.core.server.ServerConnector;

public class App {
    public static void main(String[] args) throws Exception {
        String KEYSTORE_PATH = "../keystore.p12";
        String KEYSTORE_PASSWORD = "keystorepass";
        String KEY_ALIAS = "kwikserver";

        KeyStore keystore = KeyStore.getInstance("PKCS12");

        try (FileInputStream keystoreStream = new FileInputStream(new File(KEYSTORE_PATH).getAbsolutePath())) {
            keystore.load(keystoreStream, KEYSTORE_PASSWORD.toCharArray());
        }

        Logger log = new SysOutLogger();

        log.timeFormat(Logger.TimeFormat.Long);
        log.logWarning(true);
        log.logInfo(true);
        log.logStream(true);

        List<QuicConnection.QuicVersion> supportedVersions = new ArrayList<>();
        supportedVersions.add(QuicConnection.QuicVersion.V1);

        ServerConnectionConfig config = ServerConnectionConfig.builder()
                .maxIdleTimeoutInSeconds(5000)
                .maxOpenPeerInitiatedUnidirectionalStreams(10)
                .maxOpenPeerInitiatedBidirectionalStreams(100)
                .retryRequired(true)
                .connectionIdLength(8)
                .build();

        ServerConnector connector = ServerConnector.builder()
                .withPort(7000)
                .withSupportedVersions(supportedVersions)
                .withKeyStore(keystore, KEY_ALIAS, KEYSTORE_PASSWORD.toCharArray())
                .withConfiguration(config)
                .withLogger(log)
                .build();

        connector.registerApplicationProtocol("quic", new MyQuicFactory(log));

        connector.start();
    }
}
